default_language_version:
  python: python3.12.1

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.5  # Use the latest version as of Feb 2025
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]  # Fixes issues and fails if fixes are needed
      - id: ruff-format  # Optional: Use Ruff’s formatter instead of black

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black