# Generated by Django 5.1.5 on 2025-02-01 16:43

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("customerorders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.FloatField(null=True),
        ),
    ]
